<?php
/**
 * WP Admin page for WooCommerce for Claude AI Insights.
 *
 * Registers a submenu under WooCommerce and enqueues the compiled React bundle
 * produced by `npm run build` (`build/today/index.js`). Page-load data is
 * passed via `wp_localize_script()` and read in TypeScript from
 * `window.woocommerceClaudeTodayData`.
 *
 * @package WooCommerce\Claude\Difm
 */

namespace WooCommerce\Claude\Difm;

defined( 'ABSPATH' ) || exit;

/**
 * Registers the AI Insights WP Admin page and enqueues the compiled bundle.
 *
 * PHP 7.4 compatible — no union types, no match, no enums.
 */
class DifmAdminPage {

	/**
	 * Menu slug for the admin page.
	 */
	const MENU_SLUG = 'woocommerce-claude-insights';

	/**
	 * Script handle for the compiled React bundle.
	 */
	const SCRIPT_HANDLE = 'woocommerce-claude-insights';

	/**
	 * Style handle for the compiled CSS bundle.
	 */
	const STYLE_HANDLE = 'woocommerce-claude-insights-style';

	/**
	 * Whether assets have already been enqueued this request.
	 *
	 * @var bool
	 */
	private static $enqueued = false;

	/**
	 * Register the admin menu entry and enqueue hook.
	 *
	 * @return void
	 */
	public function register() {
		add_action( 'admin_menu', array( $this, 'add_menu_page' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * Add the AI Insights submenu under WooCommerce.
	 *
	 * @return void
	 */
	public function add_menu_page() {
		add_submenu_page(
			'woocommerce',
			__( 'AI Insights', 'woocommerce-claude' ),
			__( 'AI Insights', 'woocommerce-claude' ),
			'manage_woocommerce',
			self::MENU_SLUG,
			array( $this, 'render' )
		);
	}

	/**
	 * Enqueue the compiled bundle on admin_enqueue_scripts.
	 *
	 * @param string $hook_suffix The current admin page hook suffix.
	 * @return void
	 */
	public function enqueue_assets( $hook_suffix ) {
		if ( ! $this->is_our_page( $hook_suffix ) ) {
			return;
		}
		$this->do_enqueue();
	}

	/**
	 * Perform the actual asset enqueue (idempotent — runs at most once).
	 *
	 * @return void
	 */
	private function do_enqueue() {
		if ( self::$enqueued ) {
			return;
		}
		self::$enqueued = true;

		$build_dir = WOOCOMMERCE_CLAUDE_PLUGIN_DIR . 'build/today/';
		$build_url = plugins_url( 'build/today/', WOOCOMMERCE_CLAUDE_PLUGIN_FILE );

		// Read dependencies and version from the asset file generated by wp-scripts.
		$asset_file = $build_dir . 'index.asset.php';
		$asset      = file_exists( $asset_file ) ? require $asset_file : array();
		$deps       = $asset['dependencies'] ?? array();
		$version    = $asset['version'] ?? WOOCOMMERCE_CLAUDE_VERSION;

		// Enqueue the compiled React bundle.
		wp_enqueue_script(
			self::SCRIPT_HANDLE,
			$build_url . 'index.js',
			$deps,
			$version,
			true // Load in footer.
		);

		// Enqueue the companion stylesheet (compiled from src/style.scss by webpack).
		$style_file = $build_dir . 'style-index.css';
		if ( file_exists( $style_file ) ) {
			wp_enqueue_style(
				self::STYLE_HANDLE,
				$build_url . 'style-index.css',
				array( 'wp-components' ),
				filemtime( $style_file )
			);
		}

		// Pass page-load data to the bundle.
		// Accessible in TypeScript as window.woocommerceClaudeTodayData (see src/data.ts).
		require_once WOOCOMMERCE_CLAUDE_PLUGIN_DIR . 'includes/difm/class-anthropic-client.php';

		wp_localize_script(
			self::SCRIPT_HANDLE,
			'woocommerceClaudeTodayData',
			array(
				'nonce'       => wp_create_nonce( 'wp_rest' ),
				'restBase'    => rest_url( 'woocommerce-claude/v1/difm' ),
				'settingsUrl' => admin_url( 'admin.php?page=wc-settings&tab=woocommerce-claude' ),
				'userName'    => wp_get_current_user()->display_name,
				'currency'    => get_woocommerce_currency_symbol(),
				'hasKey'      => AnthropicClient::has_api_key(),
			)
		);
	}

	/**
	 * Render the admin page mount point.
	 *
	 * WordPress calls this when the user visits WooCommerce > AI Insights.
	 * WooCommerce may replace this with its own #woocommerce-claude-insights-app container
	 * when its embedded SPA renderer is active; the React app targets that
	 * element first and falls back to #woocommerce-claude-insights-root.
	 *
	 * @return void
	 */
	public function render() {
		echo '<div id="woocommerce-claude-insights-root"></div>';
	}

	/**
	 * Whether the current admin page is our own.
	 *
	 * WC submenu pages use the hook suffix `woocommerce_page_<slug>`.
	 *
	 * @param string $hook_suffix Admin page hook suffix.
	 * @return bool
	 */
	private function is_our_page( $hook_suffix ) {
		return false !== strpos( $hook_suffix, self::MENU_SLUG );
	}
}
